# Таблица payments

In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [26]:
df_p = pd.read_csv('../raw_data/df_Payments.csv')

In [27]:
df_p.shape

(89316, 5)

In [28]:
df_p.size

446580

In [29]:
df_p.columns

Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='str')

In [30]:
df_p.info()

<class 'pandas.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_id              89316 non-null  str
 1   payment_sequential    89316 non-null  int64
 2   payment_type          89316 non-null  str
 3   payment_installments  89316 non-null  int64
 4   payment_value         89316 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 3.4 MB

In [31]:
df_p['payment_type'].nunique()

4

In [32]:
df_p['payment_type'].unique()

<StringArray>
['credit_card', 'wallet', 'voucher', 'debit_card']
Length: 4, dtype: str

In [33]:
# переведем данные в payment_type в тип "категория"
df_p['payment_type'] = df_p['payment_type'].astype('category')
df_p.info()

<class 'pandas.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_id              89316 non-null  str
 1   payment_sequential    89316 non-null  int64
 2   payment_type          89316 non-null  category
 3   payment_installments  89316 non-null  int64
 4   payment_value         89316 non-null  float64
dtypes: category(1), float64(1), int64(2), str(1)
memory usage: 2.8 MB

In [34]:
df_p['payment_sequential'].unique()

array([ 1,  8,  2,  6,  3,  4,  9,  5, 23, 11, 18, 10,  7, 12, 13, 26, 15,
       14, 17, 24, 21, 20, 16, 19, 22, 29, 25, 28])

In [35]:
df_p['payment_installments'].unique()

array([ 1,  8,  4,  2,  5,  6, 10,  3,  7,  9, 18, 12, 24, 15, 11, 13, 21,
       16, 20, 14, 17, 23, 22,  0])

In [36]:
df_p.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,Axfy13Hk4PIk,1,credit_card,1,259.14
1,v6px92oS8cLG,1,credit_card,8,382.39
2,Ulpf9skrhjfm,1,credit_card,4,249.25
3,bwJVWupf2keN,1,credit_card,2,27.79
4,Dd0QnrMk9Cj5,1,credit_card,1,76.15

In [37]:
df_p.tail()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
89311,zlcLnXGgAabl,1,wallet,1,128.00
89312,IlTAoIkILwrq,1,wallet,1,106.86
89313,uA6oXfftGVmT,1,credit_card,1,376.39
89314,v3QtU6xlGDJp,1,voucher,1,48.05
89315,Xo1fqyXOC6CR,1,credit_card,10,211.93

In [38]:
df_p.sample(10)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
923,RBmioQlQiObc,1,credit_card,2,78.50
12034,N471QMHZVUwg,1,credit_card,3,47.09
57157,HwlDFiQLHXhQ,1,credit_card,1,247.61
60038,hN3tqNsXoVFT,1,credit_card,2,330.50
33279,XRPZcTBG3aw2,1,wallet,1,134.24
20152,shoBxtim8T8G,1,credit_card,5,246.38
75326,WfzcO4ysRfGz,1,credit_card,2,139.11
48375,8JzfvO3E9gS8,1,wallet,1,383.05
33492,ajcO94w80Xgi,1,credit_card,2,225.88
80272,2xF07eWe0j2N,1,credit_card,1,436.25

In [39]:
df_p.isna().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [40]:
df_p.nunique()

order_id                89316
payment_sequential         28
payment_type                4
payment_installments       24
payment_value           25520
dtype: int64

In [41]:
df_p.duplicated().sum()

np.int64(0)

In [42]:
df_p.describe()

       payment_sequential  payment_installments  payment_value
count        89316.000000          89316.000000   89316.000000
mean             1.099646              2.965717     268.657190
std              0.772658              2.796406     344.409566
min              1.000000              0.000000       0.000000
25%              1.000000              1.000000      84.340000
50%              1.000000              2.000000     171.860000
75%              1.000000              4.000000     313.530000
max             29.000000             24.000000    7274.880000

In [43]:
# проверим, что нет оплат, не привязанных к заказам
# работать будем с df_o_clean, таблица заказов, очищенная от аномалий в датах
df_o_clean = pd.read_pickle('df_o_clean.pkl')
df_o_clean.head()

,order_id,customer_id,order_status,purchased_date,approved_at_date,delivered_date,estimated_delivery_date,dt_purchased_approved,dt_approved_delivered,dt_purchased_estimated,...,is_too_long_estimated,is_anomaly,date,year_month,year,month,day,week,day_of_week,hour
0,Axfy13Hk4PIk,hCT0x9JiGXBQ,delivered,2017-10-22 18:57:54,2017-10-22 19:14:13,2017-10-26 22:19:52,2017-11-09,0.0,4.0,17.0,...,False,False,2017-10-22,2017-10,2017,10,22,42,Sunday,18
1,v6px92oS8cLG,PxA7fv9spyhx,delivered,2018-06-20 21:40:31,2018-06-20 22:20:20,2018-07-03 22:51:22,2018-07-24,0.0,13.0,33.0,...,False,False,2018-06-20,2018-06,2018,6,20,25,Wednesday,21
2,Ulpf9skrhjfm,g3nXeJkGI0Qw,delivered,2018-02-16 16:19:31,2018-02-17 16:15:35,2018-02-27 01:29:50,2018-03-08,0.0,9.0,19.0,...,False,False,2018-02-16,2018-02,2018,2,16,7,Friday,16
3,bwJVWupf2keN,EOEsCQ6QlpIg,delivered,2018-08-18 18:04:29,2018-08-18 18:15:16,2018-08-27 20:03:51,2018-09-19,0.0,9.0,31.0,...,False,False,2018-08-18,2018-08,2018,8,18,33,Saturday,18
4,Dd0QnrMk9Cj5,mVz5LO2Vd6cL,delivered,2017-12-22 16:44:04,2017-12-22 17:31:31,2018-01-05 19:22:49,2018-01-18,0.0,14.0,26.0,...,False,False,2017-12-22,2017-12,2017,12,22,51,Friday,16

In [ ]:
merged = df_p.merge(df_o_clean, on='order_id', how='left')

unmatched = merged[merged['customer_id'].isna()]

n_unmatched = unmatched['order_id'].nunique()

share_unmatched = n_unmatched / df_p['order_id'].nunique() * 100

print(n_unmatched, end='\n')
print(round(share_unmatched, 2))

# 129 (0,14%) оплат не привязаны к заказам

129
0.14

In [ ]:
# оплаты без привязки к заказам
unmatched

# скорее всего, это те же заказы, которые даты, отмеченные как аномальные

,order_id,payment_sequential,payment_type,payment_installments,payment_value,customer_id,order_status,purchased_date,approved_at_date,delivered_date,...,is_too_long_estimated,is_anomaly,date,year_month,year,month,day,week,day_of_week,hour
571,pWRjBubXBYdq,1,wallet,1,46.52,NaN,NaN,NaT,NaT,NaT,...,NaN,NaN,NaN,NaT,NaN,NaN,NaN,<NA>,NaN,NaN
732,qf88tnNyUpRx,1,debit_card,1,75.58,NaN,NaN,NaT,NaT,NaT,...,NaN,NaN,NaN,NaT,NaN,NaN,NaN,<NA>,NaN,NaN
772,1E3iD0TBYiQv,1,credit_card,4,101.52,NaN,NaN,NaT,NaT,NaT,...,NaN,NaN,NaN,NaT,NaN,NaN,NaN,<NA>,NaN,NaN
1202,A3vUK2CgNZYI,1,credit_card,8,264.16,NaN,NaN,NaT,NaT,NaT,...,NaN,NaN,NaN,NaT,NaN,NaN,NaN,<NA>,NaN,NaN
2734,X7BdF882u7jZ,1,debit_card,1,75.58,NaN,NaN,NaT,NaT,NaT,...,NaN,NaN,NaN,NaT,NaN,NaN,NaN,<NA>,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87373,k5POw86JuOdl,1,credit_card,4,383.50,NaN,NaN,NaT,NaT,NaT,...,NaN,NaN,NaN,NaT,NaN,NaN,NaN,<NA>,NaN,NaN
87475,PLhufnwqAyZ0,1,credit_card,1,2.29,NaN,NaN,NaT,NaT,NaT,...,NaN,NaN,NaN,NaT,NaN,NaN,NaN,<NA>,NaN,NaN
87736,GrAwXMJnY6RD,1,wallet,1,23.86,NaN,NaN,NaT,NaT,NaT,...,NaN,NaN,NaN,NaT,NaN,NaN,NaN,<NA>,NaN,NaN
87897,9CgpJscKpw2I,1,credit_card,10,128.52,NaN,NaN,NaT,NaT,NaT,...,NaN,NaN,NaN,NaT,NaN,NaN,NaN,<NA>,NaN,NaN
88694,4PBMhNOtfHaJ,1,credit_card,6,17.17,NaN,NaN,NaT,NaT,NaT,...,NaN,NaN,NaN,NaT,NaN,NaN,NaN,<NA>,NaN,NaN

In [63]:
df_o_enriched = pd.read_pickle('df_o_enriched.pkl')
df_o_enriched.head()

,order_id,customer_id,order_status,purchased_date,approved_at_date,delivered_date,estimated_delivery_date,dt_purchased_approved,dt_approved_delivered,dt_purchased_estimated,is_negative_delivery_time,is_too_long_delivery_time,is_too_long_approval_time,is_too_long_estimated,is_anomaly
0,Axfy13Hk4PIk,hCT0x9JiGXBQ,delivered,2017-10-22 18:57:54,2017-10-22 19:14:13,2017-10-26 22:19:52,2017-11-09,0.0,4.0,17.0,False,False,False,False,False
1,v6px92oS8cLG,PxA7fv9spyhx,delivered,2018-06-20 21:40:31,2018-06-20 22:20:20,2018-07-03 22:51:22,2018-07-24,0.0,13.0,33.0,False,False,False,False,False
2,Ulpf9skrhjfm,g3nXeJkGI0Qw,delivered,2018-02-16 16:19:31,2018-02-17 16:15:35,2018-02-27 01:29:50,2018-03-08,0.0,9.0,19.0,False,False,False,False,False
3,bwJVWupf2keN,EOEsCQ6QlpIg,delivered,2018-08-18 18:04:29,2018-08-18 18:15:16,2018-08-27 20:03:51,2018-09-19,0.0,9.0,31.0,False,False,False,False,False
4,Dd0QnrMk9Cj5,mVz5LO2Vd6cL,delivered,2017-12-22 16:44:04,2017-12-22 17:31:31,2018-01-05 19:22:49,2018-01-18,0.0,14.0,26.0,False,False,False,False,False

In [68]:
anomaly_orders = df_o_enriched.query('is_anomaly == True')
anomaly_orders.shape[0]

129

In [82]:
sample1 = unmatched[['order_id', 'is_anomaly']]
sample2 = anomaly_orders[['order_id', 'is_anomaly']]

sample_result = pd.merge(sample1, sample2, on='order_id', how='left')
sample_result[['order_id', 'is_anomaly_y']].query('is_anomaly_y == False').is_anomaly_y.count()

np.int64(0)

In [100]:
# пересохраним датафрейм df_p, оставив только те платежи, которые есть в df_o_clean
orphan_ids = merged.loc[merged['customer_id'].isna(), 'order_id'].unique()

df_p['is_anomaly_order'] = df_p['order_id'].isin(orphan_ids)

df_p_clean = df_p.loc[~df_p['is_anomaly_order']].copy()

In [101]:
df_p_clean.drop(columns=['is_anomaly_order'], inplace=True)

In [104]:
df_p_clean.shape[0]

89187

In [ ]:
# посмотрим сколько платежей приходится на один заказ
df_p_clean.groupby('order_id').agg(cnt_orders=('order_id', 'count')).value_counts()

# одна строка в payments это одна транзакция по заказу (один зарегистрированный платеж)
# но ни payment_sequential, ни payment_installments не являются консистентными, потому что нет других строк,
# подтверждающих, что были другие взносы. Возможно, это просто агрегаты и в других таблицах (которых нет в датасете)
# можно было бы найти подтерждение тому, что было несколько способов оплаты или количество оплат

cnt_orders
1             89187
Name: count, dtype: int64

In [148]:
df_p_clean.describe()

       payment_sequential  payment_installments  payment_value
count        89187.000000          89187.000000   89187.000000
mean             1.099734              2.965724     268.664241
std              0.773135              2.795977     344.461623
min              1.000000              0.000000       0.000000
25%              1.000000              1.000000      84.375000
50%              1.000000              2.000000     171.860000
75%              1.000000              4.000000     313.530000
max             29.000000             24.000000    7274.880000

In [147]:
df_p_clean.query('payment_value == 0')

,order_id,payment_sequential,payment_type,payment_installments,payment_value
65644,gZkNlHVVt1Xp,1,credit_card,8,0.0

In [ ]:
df_o_clean.merge(df_p_clean, on='order_id').query('payment_value == 0')

# аномалия платежа, не может быть доставленный заказ быть оплаченным в 8 платежей, но в сумме 0
# помечаем как аномалию и удаляем из датафрейма

,order_id,customer_id,order_status,purchased_date,approved_at_date,delivered_date,estimated_delivery_date,dt_purchased_approved,dt_approved_delivered,dt_purchased_estimated,...,year,month,day,week,day_of_week,hour,payment_sequential,payment_type,payment_installments,payment_value
65549,gZkNlHVVt1Xp,yx8orlubNFzj,delivered,2018-07-29 16:15:14,2018-07-29 16:30:30,2018-08-13 15:07:31,2018-08-22,0.0,14.0,23.0,...,2018,7,29,30,Sunday,16,1,credit_card,8,0.0

In [159]:
# пометим заказ с нулевой суммой аномальным и исключим его из дальнейшего анализа
df_p_clean['is_anomaly_payment_value'] = df_p_clean['payment_value'] == 0
df_p_clean = df_p_clean.loc[~df_p_clean['is_anomaly_payment_value']].copy()

In [161]:
df_p_clean.drop(columns=['is_anomaly_payment_value'], inplace=True)

In [173]:
df_p_clean.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,Axfy13Hk4PIk,1,credit_card,1,259.14
1,v6px92oS8cLG,1,credit_card,8,382.39
2,Ulpf9skrhjfm,1,credit_card,4,249.25
3,bwJVWupf2keN,1,credit_card,2,27.79
4,Dd0QnrMk9Cj5,1,credit_card,1,76.15

In [ ]:
payment_types = df_p_clean.groupby('payment_type').agg(cnt_orders=('payment_type', 'count')).reset_index()
payment_types['share_pct'] = round(payment_types['cnt_orders'] / len(df_p_clean) * 100, 2)
payment_types = payment_types.sort_values('share_pct', ascending=False)
payment_types

# самые праспространенные типы оплаты это кредитная карта (>73%) и наличные деньги (>19%)

  payment_type  cnt_orders  share_pct
0  credit_card       65721      73.69
3       wallet       17276      19.37
2      voucher        4905       5.50
1   debit_card        1284       1.44

остановлиась на шаге 6
для следующего шага нужна таблица order items