# Таблица customers

In [113]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [114]:
df_c = pd.read_csv('../raw_data/df_Customers.csv')

In [115]:
df_c.shape

(89316, 4)

In [116]:
df_c.size

357264

In [117]:
df_c.columns

Index(['customer_id', 'customer_zip_code_prefix', 'customer_city',
       'customer_state'],
      dtype='str')

In [118]:
df_c.info()

<class 'pandas.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               89316 non-null  str
 1   customer_zip_code_prefix  89316 non-null  int64
 2   customer_city             89316 non-null  str
 3   customer_state            89316 non-null  str
dtypes: int64(1), str(3)
memory usage: 2.7 MB

In [119]:
df_c.head()

    customer_id  customer_zip_code_prefix       customer_city customer_state
0  hCT0x9JiGXBQ                     58125     varzea paulista             SP
1  PxA7fv9spyhx                      3112  armacao dos buzios             RJ
2  g3nXeJkGI0Qw                      4119             jandira             SP
3  EOEsCQ6QlpIg                     18212          uberlandia             MG
4  mVz5LO2Vd6cL                     88868            ilhabela             SP

In [120]:
df_c.tail()

        customer_id  customer_zip_code_prefix customer_city customer_state
89311  bfJtzkBGksdY                     94060        amparo             SP
89312  4hjsCpj6FC7g                     99835       itapevi             SP
89313  DLn56oKHl9bv                      2540     sao paulo             SP
89314  auSfRYUQUOIq                     12288      paulinia             SP
89315  rhevVNXYJnEs                     93048      brasilia             DF

In [121]:
df_c.sample(10)

,customer_id,customer_zip_code_prefix,customer_city,customer_state
47279,IkmayfqQNQft,2616,nova iguacu,RJ
70578,A3qlKMkHBnAH,38745,rio de janeiro,RJ
88781,08QGP7qNCmKB,29144,olinda,PE
59465,UhrePw1XBU6a,97037,guara,SP
6309,smURgCytVGZa,18606,itu,SP
9857,H24KHOBQsLkm,23933,sao paulo,SP
39688,7x6arHyL5NN0,53160,rio de janeiro,RJ
39868,xrJrWtJruLRY,3268,sao bernardo do campo,SP
14673,otlL8AzB9YbD,5027,itabirito,MG
44742,yA8SEnM5b3tQ,78335,pouso alegre,MG

In [122]:
df_c.info()

<class 'pandas.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               89316 non-null  str
 1   customer_zip_code_prefix  89316 non-null  int64
 2   customer_city             89316 non-null  str
 3   customer_state            89316 non-null  str
dtypes: int64(1), str(3)
memory usage: 2.7 MB

In [123]:
# переведем индекс в тип данных строка
df_c['customer_zip_code_prefix'] = df_c['customer_zip_code_prefix'].astype('str')
df_c.info()

<class 'pandas.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               89316 non-null  str
 1   customer_zip_code_prefix  89316 non-null  str
 2   customer_city             89316 non-null  str
 3   customer_state            89316 non-null  str
dtypes: str(4)
memory usage: 2.7 MB

In [124]:
# в Бразилии префикс индекса имеет 5 цифр.
# по первичной проверке head видно, что есть индексы с 4 цифрами.
df_c['customer_zip_code_prefix'].str.len().value_counts()

customer_zip_code_prefix
5    66548
4    22768
Name: count, dtype: int64

In [125]:
# посмотрим какие штаты содержат 4 цифры в индексе
zip_4 = df_c[df_c['customer_zip_code_prefix'].str.len() == 4]
states_zip_4 = (
    zip_4['customer_state']
    .dropna()
    .unique()
)
states_zip_4

<StringArray>
['RJ', 'SP', 'RN', 'BA', 'CE', 'PR', 'MG', 'PI', 'PE', 'MT', 'GO', 'SC', 'MA',
 'DF', 'RS', 'ES', 'RO', 'AL', 'PA', 'AP', 'SE', 'TO', 'PB', 'AM', 'MS', 'AC',
 'RR']
Length: 27, dtype: str

In [126]:
df_c.query('customer_state == "SP"').head(10)

     customer_id customer_zip_code_prefix    customer_city customer_state
0   hCT0x9JiGXBQ                    58125  varzea paulista             SP
2   g3nXeJkGI0Qw                     4119          jandira             SP
4   mVz5LO2Vd6cL                    88868         ilhabela             SP
6   85jiDiGSfhTu                     4762        guarulhos             SP
7   gDdkaN8b9s1g                    75870       mogi-guacu             SP
8   9Csx6oXlpLl1                    69068        bebedouro             SP
9   gZTPKLPRnreg                    20921        sao paulo             SP
13  kZ0rkJCJ6N5y                    13843  mogi das cruzes             SP
15  FrEvnEiMKGpr                    28630        sao paulo             SP
17  bUornDCZmRD4                     3440        sao paulo             SP

In [127]:
# перезапишем датафрейм и сразу установим тип данных для индекса как "строка"
df_c = pd.read_csv(
    '../raw_data/df_Customers.csv',
    dtype={'customer_zip_code_prefix': 'str'})

df_c.info()

<class 'pandas.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               89316 non-null  str
 1   customer_zip_code_prefix  89316 non-null  str
 2   customer_city             89316 non-null  str
 3   customer_state            89316 non-null  str
dtypes: str(4)
memory usage: 2.7 MB

In [128]:
df_c.head()

# проверка показала, что в исходном файле уже отсутствовали ведущие нули

    customer_id customer_zip_code_prefix       customer_city customer_state
0  hCT0x9JiGXBQ                    58125     varzea paulista             SP
1  PxA7fv9spyhx                     3112  armacao dos buzios             RJ
2  g3nXeJkGI0Qw                     4119             jandira             SP
3  EOEsCQ6QlpIg                    18212          uberlandia             MG
4  mVz5LO2Vd6cL                    88868            ilhabela             SP

In [129]:
# в Бразилии префикс индекса содержит 5 цифр. Восстановим ведущие нули
df_c['customer_zip_code_prefix'] = (
    df_c['customer_zip_code_prefix']
    .str.zfill(5)
)
df_c.head()

    customer_id customer_zip_code_prefix       customer_city customer_state
0  hCT0x9JiGXBQ                    58125     varzea paulista             SP
1  PxA7fv9spyhx                    03112  armacao dos buzios             RJ
2  g3nXeJkGI0Qw                    04119             jandira             SP
3  EOEsCQ6QlpIg                    18212          uberlandia             MG
4  mVz5LO2Vd6cL                    88868            ilhabela             SP

In [130]:
# проверим отсутствующие значения
df_c.isna().sum()

customer_id                 0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [131]:
# проверим дубликаты
df_c.duplicated().sum()

np.int64(0)

In [132]:
# проверим уникальные значения
df_c.nunique()

# количество по customer_id соответствует количеству строк в общем => таблица на уровне "кникальный клиент",
# т.е. каждому клиенту соответствует отдельная строка

customer_id                 89316
customer_zip_code_prefix    13930
customer_city                3735
customer_state                 27
dtype: int64

In [ ]:
# найдем топ штатов по числу клиентов
state_counts = (
    df_c.groupby('customer_state', as_index=False)
    .agg(customer_count=('customer_id', 'count'))
)

state_counts['share_pct'] = (
    state_counts['customer_count']
    / state_counts['customer_count'].sum()
    * 100
)

state_counts = state_counts.sort_values('customer_count', ascending=False)
state_counts.head(10)

# более 65% всех заказов приходятся на три штата: Сан-Паулу, Рио-де-Жанейро и Минас-Жерайс
# более 42% всех заказов приходится на штат Сан-Паулу
# имеем ярко выраженную концентрацию заказов в трех крупнейших штатах Юго-Востока, что типично для бразильского ecom

   customer_state  customer_count  share_pct
25             SP           37879  42.410094
18             RJ           11578  12.962963
10             MG           10334  11.570155
22             RS            4921   5.509651
17             PR            4523   5.064042
23             SC            3213   3.597340
4              BA            3088   3.457387
8              GO            1868   2.091451
7              ES            1798   2.013077
6              DF            1793   2.007479

In [ ]:
# найдем топ городов по числу заказов / клиентов
city_counts = (
    df_c.groupby('customer_city', as_index=False)
    .agg(customer_count=('customer_id', 'count'))
)

city_counts['share_pct'] = (
    city_counts['customer_count']
    / city_counts['customer_count'].sum()
    * 100
)

city_counts = city_counts.sort_values('customer_count', ascending=False)
city_counts.head(10)

# основная доля заказов отгружается в город Сан-Паулу (штат Сан-Паулу) (>16%)
# вторым по количеству заказов идет Рио-де-Жанейро (штат Рио-де-Жанейро) (~7%)
# третьим по количеству заказов идет Белу-Оризонти (штат Минас-Жирайс) (~2.7%)

              customer_city  customer_count  share_pct
3250              sao paulo           14352  16.068789
2846         rio de janeiro            6248   6.995387
398          belo horizonte            2426   2.716199
488                brasilia            1778   1.990685
1025               curitiba            1421   1.590980
2673           porto alegre            1311   1.467822
622                campinas            1304   1.459985
2934               salvador            1148   1.285324
1379              guarulhos            1067   1.194635
3095  sao bernardo do campo             839   0.939361

In [137]:
# проверим склько заказов у каждого клиента. Работать будет с df_o_clean, в котором удалены аномалии даты
df_o_clean = pd.read_pickle('df_o_clean.pkl')
df_o_clean.head()

,order_id,customer_id,order_status,purchased_date,approved_at_date,delivered_date,estimated_delivery_date,dt_purchased_approved,dt_approved_delivered,dt_purchased_estimated,is_negative_delivery_time,is_too_long_delivery_time,is_too_long_approval_time,is_too_long_estimated,is_anomaly
0,Axfy13Hk4PIk,hCT0x9JiGXBQ,delivered,2017-10-22 18:57:54,2017-10-22 19:14:13,2017-10-26 22:19:52,2017-11-09,0.0,4.0,17.0,False,False,False,False,False
1,v6px92oS8cLG,PxA7fv9spyhx,delivered,2018-06-20 21:40:31,2018-06-20 22:20:20,2018-07-03 22:51:22,2018-07-24,0.0,13.0,33.0,False,False,False,False,False
2,Ulpf9skrhjfm,g3nXeJkGI0Qw,delivered,2018-02-16 16:19:31,2018-02-17 16:15:35,2018-02-27 01:29:50,2018-03-08,0.0,9.0,19.0,False,False,False,False,False
3,bwJVWupf2keN,EOEsCQ6QlpIg,delivered,2018-08-18 18:04:29,2018-08-18 18:15:16,2018-08-27 20:03:51,2018-09-19,0.0,9.0,31.0,False,False,False,False,False
4,Dd0QnrMk9Cj5,mVz5LO2Vd6cL,delivered,2017-12-22 16:44:04,2017-12-22 17:31:31,2018-01-05 19:22:49,2018-01-18,0.0,14.0,26.0,False,False,False,False,False

In [144]:
df_o_clean.shape

(89187, 15)

In [139]:
df_o_clean.dtypes

order_id                                str
customer_id                             str
order_status                       category
purchased_date               datetime64[us]
approved_at_date             datetime64[us]
delivered_date               datetime64[us]
estimated_delivery_date      datetime64[us]
dt_purchased_approved               float64
dt_approved_delivered               float64
dt_purchased_estimated              float64
is_negative_delivery_time              bool
is_too_long_delivery_time              bool
is_too_long_approval_time              bool
is_too_long_estimated                  bool
is_anomaly                             bool
dtype: object

In [165]:
df_orcu = df_o_clean.merge(df_c, on='customer_id', how='inner')
df_orcu.head()

,order_id,customer_id,order_status,purchased_date,approved_at_date,delivered_date,estimated_delivery_date,dt_purchased_approved,dt_approved_delivered,dt_purchased_estimated,is_negative_delivery_time,is_too_long_delivery_time,is_too_long_approval_time,is_too_long_estimated,is_anomaly,customer_zip_code_prefix,customer_city,customer_state
0,Axfy13Hk4PIk,hCT0x9JiGXBQ,delivered,2017-10-22 18:57:54,2017-10-22 19:14:13,2017-10-26 22:19:52,2017-11-09,0.0,4.0,17.0,False,False,False,False,False,58125,varzea paulista,SP
1,v6px92oS8cLG,PxA7fv9spyhx,delivered,2018-06-20 21:40:31,2018-06-20 22:20:20,2018-07-03 22:51:22,2018-07-24,0.0,13.0,33.0,False,False,False,False,False,03112,armacao dos buzios,RJ
2,Ulpf9skrhjfm,g3nXeJkGI0Qw,delivered,2018-02-16 16:19:31,2018-02-17 16:15:35,2018-02-27 01:29:50,2018-03-08,0.0,9.0,19.0,False,False,False,False,False,04119,jandira,SP
3,bwJVWupf2keN,EOEsCQ6QlpIg,delivered,2018-08-18 18:04:29,2018-08-18 18:15:16,2018-08-27 20:03:51,2018-09-19,0.0,9.0,31.0,False,False,False,False,False,18212,uberlandia,MG
4,Dd0QnrMk9Cj5,mVz5LO2Vd6cL,delivered,2017-12-22 16:44:04,2017-12-22 17:31:31,2018-01-05 19:22:49,2018-01-18,0.0,14.0,26.0,False,False,False,False,False,88868,ilhabela,SP

In [ ]:
df_cnt_orders = df_orcu.groupby('customer_id').agg(cnt=('order_id', 'count')).reset_index().query('cnt > 1')
df_cnt_orders.head()

# каждому клиенту соответствует только один заказ, т.е. F=1
# дальнейший анализ по F и количеству заказов не даст сегментации

Empty DataFrame
Columns: [customer_id, cnt]
Index: []

In [172]:
# проверим согласованность между индексами и городами /штатами
df_orcu.groupby('customer_state').agg(cnt_city=('customer_city', 'count')).reset_index()

   customer_state  cnt_city
0              AC        75
1              AL       342
2              AM       139
3              AP        66
4              BA      3082
5              CE      1138
6              DF      1792
7              ES      1794
8              GO      1866
9              MA       623
10             MG     10327
11             MS       637
12             MT       847
13             PA       816
14             PB       496
15             PE      1493
16             PI       422
17             PR      4520
18             RJ     11567
19             RN       378
20             RO       241
21             RR        40
22             RS      4918
23             SC      3208
24             SE       304
25             SP     37809
26             TO       247

In [185]:
df_ind_state = (
    df_orcu.groupby('customer_zip_code_prefix')
    .agg(cnt_state=('customer_state', 'count'))
    .reset_index()
)
df_ind_state.describe()

          cnt_state
count  13924.000000
mean       6.405271
std        8.380256
min        1.000000
25%        2.000000
50%        4.000000
75%        8.000000
max      184.000000

In [183]:
df_ind_city = (
    df_orcu.groupby('customer_zip_code_prefix')
    .agg(cnt_city=('customer_city', 'count'))
    .reset_index()
)
df_ind_city.describe()

           cnt_city
count  13924.000000
mean       6.405271
std        8.380256
min        1.000000
25%        2.000000
50%        4.000000
75%        8.000000
max      184.000000

In [ ]:
df_ind_state_city = (
    df_orcu.groupby('customer_zip_code_prefix')
    .agg({'customer_city': 'nunique', 'customer_state': 'nunique'})
    .reset_index()
    .query('customer_city > 1')
)
df_ind_state_city

# проерка показывает, что аномальный данных по индексам (например, один индекс три штата) у нас нет

      customer_zip_code_prefix  customer_city  customer_state
146                      01326              2               1
572                      02611              2               1
919                      03236              2               1
1319                     03936              2               1
1887                     04745              2               1
2649                     06386              2               1
2656                     06401              2               1
3022                     07791              2               1
3599                     11088              2               1
4076                     13252              2               1
4489                     14935              2               1
5137                     19740              2               1
5293                     21380              2               1
5311                     21625              2               1
6269                     28942              2               1
6295                     29032              2               1
6596                     30664              2               1
7351                     37264              2               1
7683                     39470              2               1
8041                     44004              2               1
8867                     55590              2               1
9182                     58302              2               1
9611                     61925              2               1
9629                     62039              2               1
9993                     65180              2               1
11819                    79902              2               1
12711                    88307              2               1
12810                    88803              2               1
12815                    88810              2               1
12846                    88930              2               1
13425                    95050              2               1
13521                    95709              2               1

In [201]:
# проверим есть ли заказы без указания id клиента
missing_orders = df_o_clean[~df_o_clean['customer_id'].isin(df_c['customer_id'])]
print(f"Заказы без клиентов: {len(missing_orders)}")

Заказы без клиентов: 0

In [ ]:
city_counts = (
    df_c.groupby('customer_city', as_index=False)
    .agg(customer_count=('customer_id', 'count'))
)

city_counts['share_pct'] = (
    city_counts['customer_count']
    / city_counts['customer_count'].sum()
    * 100
)

city_counts = city_counts.sort_values('customer_count', ascending=False)
city_counts.head(10)

In [207]:
df_orcu.columns

Index(['order_id', 'customer_id', 'order_status', 'purchased_date',
       'approved_at_date', 'delivered_date', 'estimated_delivery_date',
       'dt_purchased_approved', 'dt_approved_delivered',
       'dt_purchased_estimated', 'is_negative_delivery_time',
       'is_too_long_delivery_time', 'is_too_long_approval_time',
       'is_too_long_estimated', 'is_anomaly', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='str')

In [222]:
# сравним распределение заказов и распределение клиентов по штатам
state_distr = (
    df_orcu.groupby('customer_state', as_index=False)
    .agg({'customer_id': 'nunique', 'order_id': 'nunique'})
)

state_distr = state_distr.rename(columns={
    'customer_id': 'cnt_client',
    'order_id': 'cnt_order'
})

total_clients = state_distr['cnt_client'].sum()
total_orders = state_distr['cnt_order'].sum()

state_distr['pct_client'] = (state_distr['cnt_client'] / total_clients * 100).round(2)
state_distr['pct_order'] = (state_distr['cnt_order'] / total_orders * 100).round(2)

state_distr = state_distr.sort_values('pct_client', ascending=False)
state_distr[['customer_state', 'cnt_client', 'pct_client', 'cnt_order', 'pct_order']].head()

   customer_state  cnt_client  pct_client  cnt_order  pct_order
25             SP       37809       42.39      37809      42.39
18             RJ       11567       12.97      11567      12.97
10             MG       10327       11.58      10327      11.58
22             RS        4918        5.51       4918       5.51
17             PR        4520        5.07       4520       5.07

In [ ]:
# посчитаем churn для клиентов
orders_per_cust = (
    df_orcu.groupby('customer_id', as_index=False)
    .agg(cnt_orders=('order_id', 'nunique'))
)

one_order_share = (orders_per_cust['cnt_orders'] == 1).mean()
one_order_share

# Доля клиентов с только одним заказом = 100%.
# Это означает, что датасет отражает только первый заказ каждого клиента
# (или клиенты не делают повторных покупок в наблюдаемом периоде),
# поэтому классический churn‑анализ по повторным покупкам и частоте F в RFM невозможен.
# Можно анализировать только recency и monetary
# Классический когортный анализ проводится тоже не будет, потому что нет повторных покупок

np.float64(1.0)