# Таблица customers

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [53]:
df_c = pd.read_csv('../raw_data/df_Customers.csv')

In [54]:
df_c.shape

(89316, 4)

In [55]:
df_c.size

357264

In [59]:
df_c.columns

Index(['customer_id', 'customer_zip_code_prefix', 'customer_city',
       'customer_state'],
      dtype='str')

In [60]:
df_c.info()

<class 'pandas.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               89316 non-null  str
 1   customer_zip_code_prefix  89316 non-null  int64
 2   customer_city             89316 non-null  str
 3   customer_state            89316 non-null  str
dtypes: int64(1), str(3)
memory usage: 2.7 MB

In [52]:
df_c.head()

    customer_id customer_zip_code_prefix       customer_city customer_state
0  hCT0x9JiGXBQ                    58125     varzea paulista             SP
1  PxA7fv9spyhx                    03112  armacao dos buzios             RJ
2  g3nXeJkGI0Qw                    04119             jandira             SP
3  EOEsCQ6QlpIg                    18212          uberlandia             MG
4  mVz5LO2Vd6cL                    88868            ilhabela             SP

In [5]:
df_c.tail()

        customer_id  customer_zip_code_prefix customer_city customer_state
89311  bfJtzkBGksdY                     94060        amparo             SP
89312  4hjsCpj6FC7g                     99835       itapevi             SP
89313  DLn56oKHl9bv                      2540     sao paulo             SP
89314  auSfRYUQUOIq                     12288      paulinia             SP
89315  rhevVNXYJnEs                     93048      brasilia             DF

In [6]:
df_c.sample(10)

,customer_id,customer_zip_code_prefix,customer_city,customer_state
75562,aUNJrCr5QETi,97850,senador guiomard,AC
17154,z3it23i9o79z,85907,ouro preto do oeste,RO
63841,RLOeQ1sPbkAv,89204,carapicuiba,SP
59126,0rFb8uuVAPsl,69079,cafelandia,PR
13154,PJChpETJwGwi,6142,embu-guacu,SP
30795,yA2ZdRNYY1fC,37136,betim,MG
19352,kzk5gIZINcGC,88516,sao paulo,SP
12500,YX4isR6Xpn6v,6859,maringa,PR
3290,G9KdtKAPQe8K,8615,pacaembu,SP
85472,vlmcfrwyWKNQ,77600,maua,SP

In [9]:
df_c.info()

<class 'pandas.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               89316 non-null  str
 1   customer_zip_code_prefix  89316 non-null  int64
 2   customer_city             89316 non-null  str
 3   customer_state            89316 non-null  str
dtypes: int64(1), str(3)
memory usage: 2.7 MB

In [14]:
# переведем индекс в тип данных строка
df_c['customer_zip_code_prefix'] = df_c['customer_zip_code_prefix'].astype('str')
df_c.info()

<class 'pandas.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               89316 non-null  str
 1   customer_zip_code_prefix  89316 non-null  str
 2   customer_city             89316 non-null  str
 3   customer_state            89316 non-null  str
dtypes: str(4)
memory usage: 2.7 MB

In [ ]:
# в Бразилии префикс индекса имеет 5 цифр.
# по первичной проверке head видно, что есть индексы с 4 цифрами.
df_c['customer_zip_code_prefix'].str.len().value_counts()

customer_zip_code_prefix
5    66548
4    22768
Name: count, dtype: int64

In [ ]:
# посмотрим какие штаты содержат 4 цифры в индексе
zip_4 = df_c[df_c['customer_zip_code_prefix'].str.len() == 4]
states_zip_4 = (
    zip_4['customer_state']
    .dropna()
    .unique()
)
states_zip_4

<StringArray>
['RJ', 'SP', 'RN', 'BA', 'CE', 'PR', 'MG', 'PI', 'PE', 'MT', 'GO', 'SC', 'MA',
 'DF', 'RS', 'ES', 'RO', 'AL', 'PA', 'AP', 'SE', 'TO', 'PB', 'AM', 'MS', 'AC',
 'RR']
Length: 27, dtype: str

In [44]:
df_c.query('customer_state == "SP"')

        customer_id customer_zip_code_prefix    customer_city customer_state
0      hCT0x9JiGXBQ                    58125  varzea paulista             SP
2      g3nXeJkGI0Qw                     4119          jandira             SP
4      mVz5LO2Vd6cL                    88868         ilhabela             SP
6      85jiDiGSfhTu                     4762        guarulhos             SP
7      gDdkaN8b9s1g                    75870       mogi-guacu             SP
...             ...                      ...              ...            ...
89310  xJEzC2usouPl                     5414        sao paulo             SP
89311  bfJtzkBGksdY                    94060           amparo             SP
89312  4hjsCpj6FC7g                    99835          itapevi             SP
89313  DLn56oKHl9bv                     2540        sao paulo             SP
89314  auSfRYUQUOIq                    12288         paulinia             SP

[37879 rows x 4 columns]

In [61]:
# перезапишем датафрейм и сразу установим тип данных для индекса как "строка"
df_c = pd.read_csv(
    '../raw_data/df_Customers.csv',
    dtype={'customer_zip_code_prefix': 'str'})

df_c.info()

<class 'pandas.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               89316 non-null  str
 1   customer_zip_code_prefix  89316 non-null  str
 2   customer_city             89316 non-null  str
 3   customer_state            89316 non-null  str
dtypes: str(4)
memory usage: 2.7 MB

In [ ]:
df_c.head()

# проверка показала, что в исходном файле уже отсутствовали ведущие нули

    customer_id customer_zip_code_prefix       customer_city customer_state
0  hCT0x9JiGXBQ                    58125     varzea paulista             SP
1  PxA7fv9spyhx                     3112  armacao dos buzios             RJ
2  g3nXeJkGI0Qw                     4119             jandira             SP
3  EOEsCQ6QlpIg                    18212          uberlandia             MG
4  mVz5LO2Vd6cL                    88868            ilhabela             SP

In [ ]:
# в Бразилии префикс индекса содержит 5 цифр. Восстановим ведущие нули
df_c['customer_zip_code_prefix'] = (
    df_c['customer_zip_code_prefix']
    .str.zfill(5)
)
df_c.head()

    customer_id customer_zip_code_prefix       customer_city customer_state
0  hCT0x9JiGXBQ                    58125     varzea paulista             SP
1  PxA7fv9spyhx                    03112  armacao dos buzios             RJ
2  g3nXeJkGI0Qw                    04119             jandira             SP
3  EOEsCQ6QlpIg                    18212          uberlandia             MG
4  mVz5LO2Vd6cL                    88868            ilhabela             SP

In [ ]:
# проверим отсутствующие значения
df_c.isna().sum()

customer_id                 0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [57]:
# проверим дубликаты
df_c.duplicated().sum()

np.int64(0)

In [ ]:
# проверим уникальные значения
df_c.nunique()

# количество по customer_id соответствует количеству строк в общем => таблица на уровне "кникальный клиент",
# т.е. каждому клиенту соответствует отдельная строка

customer_id                 89316
customer_zip_code_prefix    13930
customer_city                3735
customer_state                 27
dtype: int64